addon: OlliverrsTravels
deps:
  event.lua:
  - core.lua
  - db.lua
  - state.lua
  main.lua:
  - event.lua
  - minimap.lua
  minimap.lua:
  - db.lua
  - lib.lua
  - state.lua
  state.lua:
  - db.lua
libs:
  libdbicon-1.0: https://repos.wowace.com/wow/libdbicon-1-0/trunk
roots:
- main.lua
sql:
  db.sql:
  - DB.AbilityNames
  - DB.LevelData
  - DB.ZoneLevelData
  - DB.ZoneData
  - DB.CreatureNames
toc:
  Interface: 11306
  Title: Olliverr's Travels
  Notes: Utilities for hunters
  SavedVariablesPerCharacter: OlliverrsTravelsPlayerData
